# Generated by Django 5.0.6 on 2024-07-17 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True, verbose_name='название категории')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
            ],
            options={
                'verbose_name': '4. категория',
                'verbose_name_plural': '4. категории',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True, verbose_name='название магазина')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': '3. магазин',
                'verbose_name_plural': '3. магазины',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=56, unique=True, verbose_name='id сессии')),
                ('tg_id', models.CharField(default='no-auth', max_length=56, verbose_name='телеграм id')),
                ('name', models.CharField(default='no-auth', max_length=56, verbose_name='имя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('access', models.CharField(choices=[('1', 'не подтвержденный'), ('2', 'подтвержденный'), ('3', 'админ')], default=1, max_length=1)),
            ],
            options={
                'verbose_name': '1. пользователь Телеграм',
                'verbose_name_plural': '1. пользователи Телеграм',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='название бренда')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categories')),
            ],
            options={
                'verbose_name': '5. бренд',
                'verbose_name_plural': '5. бренды',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='название продукта')),
                ('amount', models.IntegerField(default=0, verbose_name='количество товара')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.brands')),
            ],
            options={
                'verbose_name': '6. товар',
                'verbose_name_plural': '6. товары',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=56, verbose_name='телеграм id')),
                ('tg_add', models.CharField(default='empty', max_length=56, verbose_name='телеграм адрес')),
                ('name', models.CharField(default='empty', max_length=56, verbose_name='имя')),
                ('second_name', models.CharField(default='empty', max_length=56, verbose_name='фамилия')),
                ('third_name', models.CharField(default='empty', max_length=56, verbose_name='отчество')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('valid', models.BooleanField(default=False, verbose_name='валидация')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.shop')),
            ],
            options={
                'verbose_name': '2. карточка сотрудника',
                'verbose_name_plural': '2. карточки сотрудников',
                'ordering': ['-created'],
            },
        ),
    ]
