# Generated by Django 5.0.6 on 2024-07-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True, verbose_name='Название магазина')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True, verbose_name='Название магазина')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=56, unique=True, verbose_name='id сессии')),
                ('tg_id', models.CharField(default='no-auth', max_length=56, verbose_name='телеграм id')),
                ('name', models.CharField(default='no-auth', max_length=56, verbose_name='имя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('valid', models.BooleanField(default=False, verbose_name='валидация')),
            ],
            options={
                'verbose_name': 'пользователь Телеграм',
                'verbose_name_plural': 'пользователи Телеграм',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=56, verbose_name='телеграм id')),
                ('tg_add', models.CharField(default='empty', max_length=56, verbose_name='телеграм адрес')),
                ('name', models.CharField(default='empty', max_length=56, verbose_name='имя')),
                ('second_name', models.CharField(default='empty', max_length=56, verbose_name='фамилия')),
                ('third_name', models.CharField(default='empty', max_length=56, verbose_name='отчество')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('valid', models.BooleanField(default=False, verbose_name='валидация')),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.position')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.shop')),
            ],
            options={
                'verbose_name': 'карточка сотрудника',
                'verbose_name_plural': 'карточки сотрудников',
                'ordering': ['-created'],
            },
        ),
    ]
