# Generated by Django 5.0.6 on 2024-07-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=56, verbose_name='телеграм id')),
                ('tg_add', models.CharField(default='empty', max_length=56, verbose_name='телеграм адрес')),
                ('name', models.CharField(default='empty', max_length=56, verbose_name='имя')),
                ('second_name', models.CharField(default='empty', max_length=56, verbose_name='фамилия')),
                ('third_name', models.CharField(default='empty', max_length=56, verbose_name='отчество')),
                ('shop', models.CharField(default='empty', max_length=56, verbose_name='адрес магазина')),
                ('position', models.CharField(default='empty', max_length=56, verbose_name='должность')),
                ('valid', models.BooleanField(default=False, verbose_name='валидация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
