# Generated by Django 5.0.6 on 2024-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'категория фирма модель',
                'verbose_name_plural': 'категории фирмы модели',
            },
        ),
    ]
