# Generated by Django 5.0.6 on 2024-07-18 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='prise',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена за штуку'),
        ),
        migrations.AlterField(
            model_name='deals',
            name='tota_prise',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='итоговая цена'),
        ),
    ]
