# Generated by Django 5.0.6 on 2024-07-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='data',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=56, unique=True, verbose_name='название категории'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=56, unique=True, verbose_name='название магазина'),
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True, verbose_name='название бренда')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categories')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True, verbose_name='название продукта')),
                ('amount', models.IntegerField(default=0, verbose_name='количество товара')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.brands')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['-created'],
            },
        ),
    ]
