# Generated by Django 5.0.6 on 2024-07-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_categories_options_remove_categories_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=56, verbose_name='название бренда'),
        ),
    ]
